#!/bin/sh

#GO to iGenomes folder
#cd /illumina/runs/iGenomes
G=$1`echo "*.fa"`

Genome=`find /illumina/runs/iGenomes -type f -name "$G" -print`
echo "------------------------------------------------------------------------------------------------------"
echo "Genome to USE: $Genome"
echo "------------------------------------------------------------------------------------------------------"
echo "VERIFY the name of desired reference sequence IF OK, press ENTER to continue, if NOT press N and ENTER"
echo "------------------------------------------------------------------------------------------------------"
read opt
if [ "$opt" ==  "" ];
then
#CONSTRUCT PATH TO bt2 files and fa files for genome
iGenome="/"
FAPath=$iGenome${Genome:1}
echo "FAPath: $FAPath"
BTPath=${FAPath%???}
echo "BTPath: $BTPath"
date >> AlignmentReference.txt
echo "FAPath: $FAPath" >>  AlignmentReference.txt 

#END OF REF SEARCH
fi

#READ FOLDER LIST

DIRLIST=$(find . -maxdepth 1 -mindepth 1 -type d -exec basename {} \;)

echo "FOUND SAMPLE FOLDERS : $DIRLIST"

for folder in ${DIRLIST[@]}
do
cd $folder
pwd

#reading of generated trimmed files
FN=""
for i in T*.gz; do FN=`echo $FN$i,`; done
FN="${FN%?}"
echo "BOWTIE 2 file list : $FN"
nohup bowtie2  --no-1mm-upfront -D 15 -R 2 -N 0 -L 10 -i S,1,1.15   -p 16 -x $BTPath  -U $FN -S tmp.sam  --un-gz Non_rtRNA_$folder.fastq.gz > nohup_bowtieL10EtoE_rtRNA_$folder.out 

#SORTING
echo "SORTING and CONVERSION to BAM"
samtools view -bS  tmp.sam | samtools sort -o tempbam.bam

#KEEP ONLY MAPPED READS
echo "KEEP only MAPPED READS"
samtools view -h -F 4 -b tempbam.bam > mapped_RNA.bam
samtools view -h  mapped_RNA.bam > mapped_RNA.sam

rm tmp.sam
rm tempbam.bam

grep -E "@|NM:" mapped_RNA.sam | grep -v "XS:" > unique_RNA_$folder.sam
echo "COUNTING OF COVERAGE"
samtools mpileup -f $FAPath -aBQ0 -d10000000 unique_RNA_$folder.sam | cut -f1-4 > coverage_mpileup_$folder.csv

#Counting of RNA counts
echo "COUNTING"
awk '{print $3}' unique_RNA_$folder.sam | sort | uniq -c | awk '{print $3,$2,$1,$4}' | sort -n > unique_RNA_count_$folder.csv

#CREATE A LIST OF RNAS to treat
echo "CREATE A LIST OF RNAs, ONLY WITH OVER 100 counts retained"
awk '{print $3}'  mapped_RNA.sam | sort | uniq -c | awk '{print $3,$2,$1,$4}' > Count_RNA_$folder.csv
awk '(NR>0) && ($2 > 100 ) ' Count_RNA_$folder.csv | sort -nrk 2,2  >  Sorted_Count_RNA_$folder.csv
awk '{print $1}' Sorted_Count_RNA_$folder.csv > RNA_list.csv
rm Count_RNA_$folder.csv
rm mapped_RNA.sam

samtools view -Sb  unique_RNA_$folder.sam > unique_RNA_$folder.bam
samtools index  unique_RNA_$folder.bam

echo "CONVERSION TO BED"
bedtools bamtobed -i  unique_RNA_$folder.bam > mapped_RNA.bed 

#READING from file the RNAs names line by line
while read -r RNA
do
echo -e "read value : $RNA"

#RNA_name=$(echo "${RNA%?}")
RNA_name=$RNA
echo "tRNA_name : $RNA_name"

#SEPARATE COUNTS FOR selected tRNAs
echo "SEPARATE COUNTS by tRNA db number"
grep -w "$RNA_name" mapped_RNA.bed > mapped_RNA_$RNA_name.bed
#COUNTING
echo "COUNTING 5'-ends"

awk '{print $2}' mapped_RNA_$RNA_name.bed | sort | uniq -c | awk '{print $3,$2,$1,$4}' | sort -n > UCount5prime_$RNA_name.csv
rm mapped_RNA_$RNA_name.bed

#SPLIT COVERAGE by RNA
grep -w "$RNA_name" coverage_mpileup_$folder.csv > coverage_$RNA_name.csv
done < RNA_list.csv

#CLEAN UP
rm mapped_RNA.bam
rm  mapped_RNA.bed
rm unique_RNA_$folder.sam

cd ..
done









