#!/bin/sh

#trimming 8-50 nt STR 7 /TruSeq3-SE.fa:2:30:7 
for i in `find *.gz`
do
# //!\\
java -jar /Path/To/Trimmomatic-version/trimmomatic-version.jar SE -phred33 $i T0850Q30_$i ILLUMINACLIP:/Path/To/Trimmomatic-version/adapters/TruSeq3-SE.fa:2:30:7 LEADING:30 TRAILING:30 SLIDINGWINDOW:4:15 MINLEN:8 AVGQUAL:30
done


